services:
  bot-detect:
    build: .
    network_mode: 'host'
    ports:
      - 3000
    environment:
      - DB_DRIVER=postgresql
      - DB_URL=postgresql://app:app@postgres:5432/app
    command:
      - '--port'
      - '3000'

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    network_mode: 'host'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app